### ISSUE TITLE
Add link to site in repo's "About" section

### ISSUE THREAD

**Issue by jtoar** [adriatic/tandem#4]
@adriatic could you add a link to the site (https://rw-community.org/) in the repo's "About" section to make it easier to view? Thanks!

![image](https://user-images.githubusercontent.com/32992335/163955269-c7d6009c-b781-4a9e-8343-604db4c4ea78.png)

**Comment by adriatic** [comment]
@jtoar 

> @adriatic could you add a link to the site (https://rw-community.org/) in the repo's "About" section to make it easier to view? Thanks!
> 
> ![image](https://user-images.githubusercontent.com/32992335/163955269-c7d6009c-b781-4a9e-8343-604db4c4ea78.png)

Done 😃

**Comment by jtoar** [comment]
@adriatic thanks!
